### ISSUE TITLE
read_dma_raw broken

### ISSUE THREAD

**Issue by lbutkows** [ChimeraTK/MatlabTools#5]
After updating: mtca4u-matlab-tools (00.04.15-xenial1) over (00.04.11-xenial2)
The function read_dma_raw stopped to work properly.
- function works properly when given initial offset is 0, in other cases data look mixed.
- some data in stream are taken with different offset addresses, some data are 0

Some first analysis shows that offset format has changed from bytes to dwords, also the return value format of the function has changed.

Now it might be proper but it breaks compatibility to previous version.

**Comment by lbutkows** [comment]
I did more checking:
1. It looks that offset format has changed (unification is fine all in bytes or all in dwords)

2. The return value format has changed.
I see that the format was always double so 64bit but in previous version there was no negative numbers. So data was taken as uint32 and placed into double. Now it looks we have int32 which it is placed into double.
I checked the code and I was not aware of additional function parameters like sign. When setting sign to 1 then I have the same behavior. So it looks now default is sign = 1 but was sign = 0.

So not exactly bugs but it broke compatibility and my scripts stopped working properly.

**Comment by killenb** [comment]
Information for solving the ticket:

- The change was introduced in mtca4u_mex.cpp between 00.04.11 and 00.04.15. It was necessary because the original implementation was using the deprecated original RegisterAccessor with the templated read-functions.

There are two interface changes:
1. The offset has changed. It was in bytes and now is in words. (I think ?) As I understand it this change was not intended and I would consider this the bug.
2. The interpretation signed/unsigned changed. The correct behaviour is that it should take what is in the map file (signed if not specified). If this was not the case it was a bug before.

Please study the code and verify these statements.

For 1) we have to check which the intended interface is. For 2) I would consider it a bug in the map file if the unsigned is wanted but it is signed. It should be fixed there if this is the case and the matlab tools correctly display this (cross check with QtHardMon).

**Comment by killenb** [comment]
readRaw returns an array of double. This is wrong. You need to return an array of int32. Otherwise bit operations (e.g. splitting into 16 bit words) is not possible.

**Comment by vargheseg** [comment]
It is possible to use a double for bit operations with the `assumedtype` parameter 

```
>>a = 2
>> class (a)
ans =
double
>>>> bitshift(a, 1, 'uint32')
ans =
     4
```

**Comment by vargheseg** [comment]
Also do we want to restrict to 32 bits now that 64 bits is also a supported type by the framework; would it make sense to use a 64 bit accessor.

**Comment by killenb** [comment]
Unfortunately in our current interface raw means int32. If you use read_raw that implicitly means you always get int32. It does not make sense to return anything else in this function.
This has nothing to do with int64 being supported by the regular interface. This also supports double, float and bool. But raw is a different interface and this is always int32. (I am repeating myself...)

**Comment by vargheseg** [comment]
read_raw changed to  return  a matlab array with classid: int32 (https://github.com/ChimeraTK/MatlabTools/commit/713a76ef05a8997d618118d23ead8bfa1fe05920)

**Comment by killenb** [comment]
How does Matlab know what type it is if you just ctype_cast (reinterpret_cast) the pointer to the memory? You should use memcpy instead of the loop. That's one of the reasons to use the int32 data type (raw also means 100 % binary equivalent)

**Comment by vargheseg** [comment]
code uses reinterpret_cast and memcpy now https://github.com/ChimeraTK/MatlabTools/commit/ecc07e3b13bb3236de28a87f43513d8fdf34c9f0
